name: Deploy to Production

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.2.3)'
        required: true
        type: string

env:
  FLUTTER_VERSION: '3.16.0'

jobs:
  validate-release:
    name: Validate Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION="${{ github.ref_name }}"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Validate version format
      run: |
        if ! [[ "${{ steps.version.outputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version format. Expected: v1.2.3"
          exit 1
        fi

  test:
    name: Run Full Test Suite
    uses: ./.github/workflows/flutter-test.yml

  build-android:
    name: Build Android Bundle
    needs: [validate-release, test]
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: pod_app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable
        cache: true

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Get dependencies
      run: flutter pub get

    - name: Configure Firebase (Production)
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON_PRODUCTION }}
      run: |
        echo "$GOOGLE_SERVICES_JSON" | base64 -d > android/app/google-services.json

    - name: Update version
      run: |
        VERSION="${{ needs.validate-release.outputs.version }}"
        VERSION_NUMBER="${VERSION#v}"
        BUILD_NUMBER=${{ github.run_number }}
        
        # Update pubspec.yaml
        sed -i "s/version: .*/version: $VERSION_NUMBER+$BUILD_NUMBER/" pubspec.yaml

    - name: Build App Bundle
      env:
        KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      run: |
        echo "$KEYSTORE" | base64 -d > android/upload-keystore.jks
        
        # Create key.properties
        cat > android/key.properties << EOF
        storePassword=$KEYSTORE_PASSWORD
        keyPassword=$KEY_PASSWORD
        keyAlias=$KEY_ALIAS
        storeFile=../../upload-keystore.jks
        EOF
        
        flutter build appbundle --release \
          --dart-define=ENVIRONMENT=production \
          --dart-define=REPLICATE_API_URL=https://api.printcraft.ai \
          --obfuscate --split-debug-info=build/symbols

    - name: Upload to Google Play Console
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
        packageName: com.appyfly.app
        releaseFiles: pod_app/build/app/outputs/bundle/release/app-release.aab
        track: production
        status: completed
        releaseNotesFile: RELEASE_NOTES.md
        mappingFile: pod_app/build/app/outputs/mapping/release/mapping.txt
        debugSymbols: pod_app/build/symbols

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-release-${{ needs.validate-release.outputs.version }}
        path: |
          pod_app/build/app/outputs/bundle/release/app-release.aab
          pod_app/build/app/outputs/mapping/release/mapping.txt
          pod_app/build/symbols

  build-ios:
    name: Build iOS App
    needs: [validate-release, test]
    runs-on: macos-latest
    
    defaults:
      run:
        working-directory: pod_app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable
        cache: true

    - name: Get dependencies
      run: flutter pub get

    - name: Configure Firebase (Production)
      env:
        GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_PRODUCTION }}
      run: |
        echo "$GOOGLE_SERVICE_INFO_PLIST" | base64 -d > ios/Runner/GoogleService-Info.plist

    - name: Update version
      run: |
        VERSION="${{ needs.validate-release.outputs.version }}"
        VERSION_NUMBER="${VERSION#v}"
        BUILD_NUMBER=${{ github.run_number }}
        
        # Update Info.plist
        /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION_NUMBER" ios/Runner/Info.plist
        /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" ios/Runner/Info.plist

    - name: Install Apple Certificate
      env:
        P12_CERTIFICATE: ${{ secrets.IOS_P12_CERTIFICATE_PRODUCTION }}
        P12_PASSWORD: ${{ secrets.IOS_P12_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}
        PROVISIONING_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE_PRODUCTION }}
      run: |
        # Create keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security set-keychain-settings -t 3600 -u build.keychain
        
        # Import certificate
        echo "$P12_CERTIFICATE" | base64 -d > certificate.p12
        security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
        
        # Install provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "$PROVISIONING_PROFILE" | base64 -d > ~/Library/MobileDevice/Provisioning\ Profiles/production.mobileprovision

    - name: Build IPA
      run: |
        flutter build ipa --release --export-options-plist=ios/ExportOptionsProduction.plist \
          --dart-define=ENVIRONMENT=production \
          --dart-define=REPLICATE_API_URL=https://api.printcraft.ai \
          --obfuscate --split-debug-info=build/symbols

    - name: Upload to App Store Connect
      env:
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
      run: |
        echo "$APP_STORE_CONNECT_API_KEY" > private_key.p8
        
        xcrun altool --upload-app -f build/ios/ipa/*.ipa \
          --type ios \
          --apiKey "$APP_STORE_CONNECT_API_KEY_ID" \
          --apiIssuer "$APP_STORE_CONNECT_ISSUER_ID" \
          --private-key @file:private_key.p8
        
        rm -f private_key.p8

    - name: Cleanup keychain
      if: always()
      run: |
        security delete-keychain build.keychain || true
        rm -f certificate.p12

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios-release-${{ needs.validate-release.outputs.version }}
        path: |
          pod_app/build/ios/ipa/*.ipa
          pod_app/build/symbols

  deploy-backend:
    name: Deploy Backend Services
    needs: [validate-release, test]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy Firebase Functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        npm install -g firebase-tools
        firebase use production --token "$FIREBASE_TOKEN"
        firebase deploy --only functions,firestore:rules,storage:rules --token "$FIREBASE_TOKEN" --non-interactive

    - name: Update Remote Config
      env:
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS=service-account.json
        
        # Update remote config with new version
        node scripts/update-remote-config.js --version "${{ needs.validate-release.outputs.version }}"
        
        rm -f service-account.json

  create-release:
    name: Create GitHub Release
    needs: [validate-release, build-android, build-ios, deploy-backend]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.validate-release.outputs.version }}
        name: Release ${{ needs.validate-release.outputs.version }}
        body_path: RELEASE_NOTES.md
        files: |
          android-release-*/app-release.aab
          ios-release-*/*.ipa
        generate_release_notes: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify-release:
    name: Notify Release Status
    needs: [create-release]
    if: always()
    runs-on: ubuntu-latest

    steps:
    - name: Send Slack notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: |
          🚀 Production Release ${{ needs.validate-release.outputs.version }}
          Status: ${{ job.status == 'success' && '✅ Successful' || '❌ Failed' }}
          
          Android: ${{ needs.build-android.result }}
          iOS: ${{ needs.build-ios.result }}
          Backend: ${{ needs.deploy-backend.result }}
          
          Release Notes: https://github.com/${{ github.repository }}/releases/tag/${{ needs.validate-release.outputs.version }}
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: ${{ secrets.SLACK_WEBHOOK_URL != '' }}

    - name: Update status page
      if: success()
      run: |
        curl -X POST https://api.statuspage.io/v1/pages/${{ secrets.STATUSPAGE_PAGE_ID }}/incidents \
          -H "Authorization: OAuth ${{ secrets.STATUSPAGE_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "incident": {
              "name": "Release ${{ needs.validate-release.outputs.version }} Deployed",
              "status": "resolved",
              "impact": "none",
              "body": "Successfully deployed version ${{ needs.validate-release.outputs.version }} to production."
            }
          }'